### ISSUE TITLE
Grid in plot2D

### ISSUE THREAD

**Issue by nk448** [lgatto/pRoloc#104]
Hi,
would it be possible to have the option of adding/removing the grid in plot2D, please?

**Comment by lmsimp** [comment]
Thanks for adding the issue Nina, actually, it may well be a better solution to just adapt the code for your own use rather than adding the option to `plot2D`. I have modified `plot2D` for you see the code `plot2D_mod` [here](https://gist.github.com/lmsimp/1436be73bb19170fdbac22bb87bcf552). 

To run:

```r
library(“pRoloc”)
library(“pRolocdata”)
data("hyperLOPIT2015")
plot2D_mod(hyperLOPIT2015)
```

**Comment by lgatto** [comment]
You can also type 
```r
source("https://gist.githubusercontent.com/lmsimp/1436be73bb19170fdbac22bb87bcf552/raw/e3c4dc2c9b0e8fa9885baa7d9673cc5ae68a2734/plot2D_mod")
```
and `plot2D_mod` use it right away.

**Comment by nk448** [comment]
Great, than you!
