### ISSUE TITLE
Travis deployment

### ISSUE THREAD

**Issue by lgatto** [lgatto/pRoloc#119]
Struggling with the travis deployment
```
── Building articles ───────────────────────────────────────────────────────────
Writing 'articles/index.html'
Reading 'vignettes/v01-pRoloc-tutorial.Rmd'
<simpleError in packageVersion(pkg): package ‘pRoloc’ not found>
Error in packageVersion(pkg) : package ‘pRoloc’ not found
Calls: <Anonymous> -> build_site_external -> <Anonymous> -> get_result
Execution halted
/home/travis/.travis/job_stages: line 415: 14479 Terminated              travis_jigger "${!}" "${timeout}" "${cmd[@]}"
```
See https://travis-ci.org/lgatto/pRoloc/jobs/448770297#L1431

@sgibb - do you have an idea?

**Comment by sgibb** [comment]
That's wired. I can't reproduce the error on my computer. Unfortunately I don't know why `pkgdown::build_site()` fails, here. I tried to use `pkgdown` and `pkgload` from github but this dosn't solve the problem: https://travis-ci.org/sgibb/pRoloc/builds/449280295

This error seems stupid because `pRoloc` was successfully loaded a few lines before.

**Comment by lgatto** [comment]
> This error seems stupid because `pRoloc` was successfully loaded a few lines before.

Exactly! 

Neither can I locally. Oh dear...

**Comment by lgatto** [comment]
Or could it be related to Bioc being in the middle of a release? If so, the current build should work. Crossing my fingers.

**Comment by sgibb** [comment]
JFTR I have the same error for `cleaver`: https://travis-ci.org/sgibb/cleaver/jobs/450230056#L1412 (it doesn't fail but produce a 404 instead of a vignette).
